import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

const SEED_JOBS = [
  { title: 'ML Engineer — LLM Fine-tuning', company: 'Stealth AI Startup', platform: 'Upwork', skills: ['Python', 'Fine-tuning', 'PyTorch', 'HuggingFace Transformers', 'Prompt Engineering'], rate_min: 80, rate_max: 120, description: 'Fine-tune open-source LLMs (Mistral, Llama) on proprietary datasets. Must have hands-on experience with LoRA/QLoRA. Remote, 3-month contract.', url: 'https://www.upwork.com' },
  { title: 'Senior Data Scientist — NLP/Text Analytics', company: 'FinTech Corp', platform: 'Toptal', skills: ['Python', 'NLP', 'Machine Learning', 'SQL', 'Data Science'], rate_min: 100, rate_max: 150, description: 'Build text classification and sentiment models for financial documents. 6-month engagement. Python, spaCy, transformers.', url: 'https://www.toptal.com' },
  { title: 'RAG Pipeline Engineer', company: 'LegalTech SaaS', platform: 'Freelancer', skills: ['Python', 'RAG Pipelines', 'Prompt Engineering', 'FastAPI', 'Docker'], rate_min: 70, rate_max: 100, description: 'Design and implement a Retrieval-Augmented Generation pipeline over legal documents. Pinecone or Weaviate. FastAPI backend.', url: 'https://www.freelancer.com' },
  { title: 'Computer Vision Consultant', company: 'Manufacturing Inc', platform: 'Gun.io', skills: ['Python', 'Computer Vision', 'Deep Learning', 'PyTorch', 'Docker'], rate_min: 90, rate_max: 130, description: 'Implement defect detection system using YOLO and custom CNNs. Dataset labeling pipeline required. On-site possible for kickoff.', url: 'https://gun.io' },
  { title: 'MLOps Engineer — AWS SageMaker', company: 'E-commerce Platform', platform: 'Upwork', skills: ['MLOps / LLMOps', 'Python', 'Cloud (AWS/GCP/Azure)', 'Docker', 'Machine Learning'], rate_min: 85, rate_max: 115, description: 'Set up end-to-end ML pipelines on AWS SageMaker. CI/CD for models, monitoring, drift detection. 4-month contract.', url: 'https://www.upwork.com' },
  { title: 'Prompt Engineer & AI Product Consultant', company: 'Agency (Multiple Clients)', platform: 'Contra', skills: ['Prompt Engineering', 'Python', 'RAG Pipelines'], rate_min: 60, rate_max: 90, description: 'Help clients integrate GPT-4/Claude into their SaaS products. System prompt design, function calling, evaluation frameworks.', url: 'https://contra.com' },
  { title: 'Data Engineer — ML Feature Store', company: 'Retail Analytics Co', platform: 'Toptal', skills: ['Data Engineering', 'Python', 'SQL', 'Cloud (AWS/GCP/Azure)', 'Machine Learning'], rate_min: 80, rate_max: 110, description: 'Build and maintain a feature store (Feast) for real-time ML inference. Spark, Kafka, Redshift. Long-term engagement.', url: 'https://www.toptal.com' },
  { title: 'AI Research Engineer — Multimodal Models', company: 'AI Research Lab', platform: 'Braintrust', skills: ['Deep Learning', 'Python', 'PyTorch', 'Machine Learning', 'Computer Vision', 'NLP'], rate_min: 120, rate_max: 180, description: 'Contribute to research on multimodal LLMs. Experience with CLIP, BLIP-2, or LLaVA preferred. Publish-quality work expected.', url: 'https://www.braintrust.dev' },
  { title: 'Recommendation System Engineer', company: 'Streaming Platform', platform: 'Upwork', skills: ['Machine Learning', 'Python', 'Data Engineering', 'SQL', 'Deep Learning'], rate_min: 75, rate_max: 105, description: 'Build collaborative and content-based filtering models. A/B testing framework. Python, Spark, Elasticsearch.', url: 'https://www.upwork.com' },
  { title: 'NLP Engineer — Chatbot & Intent Recognition', company: 'Telecom Company', platform: 'Freelancer', skills: ['NLP', 'Python', 'Machine Learning', 'Deep Learning'], rate_min: 65, rate_max: 90, description: 'Build intent classification and entity extraction for a customer-service chatbot. Rasa or Dialogflow integration.', url: 'https://www.freelancer.com' },
  { title: 'LLMOps / AI Infrastructure Engineer', company: 'Series B AI Startup', platform: 'Turing', skills: ['MLOps / LLMOps', 'Python', 'Docker', 'Cloud (AWS/GCP/Azure)', 'Prompt Engineering'], rate_min: 95, rate_max: 135, description: 'Own LLM deployment infrastructure: vLLM, TGI, model quantization, autoscaling. Kubernetes required. Full-time contract.', url: 'https://turing.com' },
  { title: 'Freelance ML Instructor — Online Course', company: 'EdTech Platform', platform: 'Contra', skills: ['Machine Learning', 'Python', 'Deep Learning', 'Data Science'], rate_min: 50, rate_max: 80, description: 'Create and record a 20-hour video course on practical ML with scikit-learn and PyTorch. Flexible schedule, revenue share.', url: 'https://contra.com' },
  { title: 'Time Series Forecasting Engineer', company: 'Energy Sector Client', platform: 'Toptal', skills: ['Machine Learning', 'Python', 'Data Science', 'SQL', 'Data Engineering'], rate_min: 85, rate_max: 120, description: 'Build demand forecasting models (Prophet, LSTM, N-BEATS) for electricity load prediction. 3-month project.', url: 'https://www.toptal.com' },
  { title: 'AI Safety & Evaluation Researcher', company: 'AI Safety Non-profit', platform: 'Braintrust', skills: ['Prompt Engineering', 'Python', 'Machine Learning', 'NLP'], rate_min: 70, rate_max: 100, description: 'Design evaluation benchmarks and red-teaming protocols for LLMs. Familiarity with RLHF and constitutional AI helpful.', url: 'https://www.braintrust.dev' },
  { title: 'Python/FastAPI Backend for AI App', company: 'SaaS Startup', platform: 'Upwork', skills: ['FastAPI', 'Python', 'Docker', 'Cloud (AWS/GCP/Azure)', 'Prompt Engineering'], rate_min: 60, rate_max: 85, description: 'Build REST API layer to serve ML models and LLM completions. PostgreSQL, Redis, Docker, AWS Lambda.', url: 'https://www.upwork.com' },
  { title: 'Kaggle-style Competition Consultant', company: 'Insurance Analytics', platform: 'Freelancer', skills: ['Machine Learning', 'Python', 'Data Science', 'Deep Learning', 'SQL'], rate_min: 55, rate_max: 80, description: 'Optimize ML models for tabular claims data. XGBoost, LightGBM, CatBoost. Provide a reproducible notebook deliverable.', url: 'https://www.freelancer.com' },
  { title: 'AI Product Manager (Technical)', company: 'B2B SaaS', platform: 'Contra', skills: ['Prompt Engineering', 'Machine Learning', 'Data Science'], rate_min: 80, rate_max: 120, description: 'Define product requirements for AI-powered features. Bridge engineering and stakeholders. ML background essential for credibility.', url: 'https://contra.com' },
  { title: 'Speech Recognition & TTS Engineer', company: 'Voice AI Startup', platform: 'Turing', skills: ['Deep Learning', 'Python', 'NLP', 'PyTorch'], rate_min: 80, rate_max: 115, description: 'Work on ASR (Whisper fine-tuning) and TTS (VITS, Bark) pipelines. Real-time streaming inference a plus.', url: 'https://turing.com' },
  { title: 'Generative AI — Image/Video Models', company: 'Creative Agency', platform: 'Upwork', skills: ['Deep Learning', 'Python', 'Computer Vision', 'PyTorch', 'Fine-tuning'], rate_min: 75, rate_max: 110, description: 'Fine-tune Stable Diffusion / SDXL / FLUX for brand-consistent image generation. ControlNet, IP-Adapter experience a plus.', url: 'https://www.upwork.com' },
  { title: 'Fraud Detection ML Engineer', company: 'Payments Startup', platform: 'Gun.io', skills: ['Machine Learning', 'Python', 'Data Engineering', 'SQL', 'Deep Learning'], rate_min: 90, rate_max: 130, description: 'Build real-time fraud scoring models. Imbalanced datasets, graph neural networks, streaming features. Kafka + Flink.', url: 'https://gun.io' },
  { title: 'Hugging Face / Transformers Engineer', company: 'NLP Product Co', platform: 'Toptal', skills: ['NLP', 'Python', 'HuggingFace Transformers', 'Deep Learning', 'Fine-tuning', 'PyTorch'], rate_min: 85, rate_max: 125, description: 'Adapt pre-trained transformers for domain-specific tasks. Training, evaluation, ONNX export and inference optimization.', url: 'https://www.toptal.com' },
  { title: 'Data Annotation & Pipeline Lead', company: 'AI Data Services', platform: 'Freelancer', skills: ['Machine Learning', 'Python', 'Data Engineering', 'SQL'], rate_min: 45, rate_max: 65, description: 'Manage labeling pipeline for CV and NLP datasets. Define annotation guidelines, QA processes, tooling (Label Studio).', url: 'https://www.freelancer.com' },
  { title: 'LLM Evaluation & Red-teaming Engineer', company: 'Enterprise AI Platform', platform: 'Braintrust', skills: ['Prompt Engineering', 'Python', 'NLP', 'Machine Learning'], rate_min: 90, rate_max: 130, description: 'Build systematic evaluation harnesses (RAGAS, custom metrics) and adversarial test suites for production LLM deployments.', url: 'https://www.braintrust.dev' },
  { title: 'Graph ML / Knowledge Graph Engineer', company: 'Pharma Research', platform: 'Upwork', skills: ['Machine Learning', 'Python', 'Deep Learning', 'PyTorch', 'Data Science'], rate_min: 95, rate_max: 140, description: 'Build GNN-based models over drug-protein interaction graphs. Neo4j, PyG (PyTorch Geometric). Publications a bonus.', url: 'https://www.upwork.com' },
  { title: 'AI Automation Consultant — n8n / Zapier + LLMs', company: 'Operations Consultancy', platform: 'Contra', skills: ['Prompt Engineering', 'Python', 'FastAPI'], rate_min: 50, rate_max: 75, description: 'Automate business workflows using LLM agents, n8n, and custom Python scripts. No-code + code hybrid projects.', url: 'https://contra.com' },
]

export async function GET() {
  const supabase = await createClient()

  const jobs = SEED_JOBS.map(j => ({
    ...j,
    location: 'Remote',
    employment_type: 'contract' as const,
    posted_at: new Date(Date.now() - Math.random() * 14 * 24 * 60 * 60 * 1000).toISOString(),
  }))

  const { error } = await supabase.from('jobs').insert(jobs)

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json({ ok: true, inserted: jobs.length })
}
